
import http from 'k6/http';
import { check, sleep } from 'k6';
import { randomString } from 'https://jslib.k6.io/k6-utils/1.2.0/index.js';

export const options = {
    thresholds: {
        http_req_failed: ['rate<0.01'], // http errors should be less than 1%
        http_req_duration: ['p(95)<500'], // 95% of requests should be below 500ms
    },
    scenarios: {
        guest_browsing: {
            executor: 'constant-vus',
            vus: 10,
            duration: '30s',
            exec: 'guestBrowsing',
        },
        student_exam: {
            executor: 'ramping-vus',
            startVUs: 0,
            stages: [
                { duration: '10s', target: 5 },
                { duration: '20s', target: 5 },
                { duration: '10s', target: 0 },
            ],
            gracefulRampDown: '0s',
            exec: 'studentExam',
        },
        admin_actions: {
            executor: 'shared-iterations',
            vus: 1,
            iterations: 5,
            maxDuration: '30s',
            exec: 'adminActions',
        },
    },
};

const BASE_URL = 'http://localhost:3000';

export function guestBrowsing() {
    const res = http.get(`${BASE_URL}/api/teacher/lessons`);
    check(res, {
        'lessons status is 200': (r) => r.status === 200,
        'lessons body is array': (r) => Array.isArray(r.json()),
    });
    sleep(1);
}

export function studentExam() {
    // 1. List exams
    const listRes = http.get(`${BASE_URL}/api/admin/exams`);
    check(listRes, {
        'exam list status is 200': (r) => r.status === 200,
    });

    const exams = listRes.json();
    if (exams.length > 0) {
        const examId = exams[0].id;

        // 2. Submit attempt (Randomized)
        const payload = JSON.stringify({
            examId: examId,
            studentName: `Student-${randomString(5)}`,
            score: Math.floor(Math.random() * 100),
            answers: {
                "q1": "print('hello')",
                "q2": "return True"
            }
        });

        const params = {
            headers: {
                'Content-Type': 'application/json',
            },
        };

        const submitRes = http.post(`${BASE_URL}/api/exam/submit`, payload, params);

        check(submitRes, {
            'submit status is 200': (r) => r.status === 200,
            'submit success': (r) => r.json('success') === true,
        });
    }
    sleep(2);
}

export function adminActions() {
    const newExamId = `k6-test-${randomString(8)}`;
    const payload = JSON.stringify({
        id: newExamId,
        title: `K6 Load Test Exam ${newExamId}`,
        description: "Generated by k6 load testing script",
        durationMinutes: 45,
        isPublic: false,
        questions: [
            {
                id: "q1",
                title: "Test Question",
                description: "Solve this.",
                initialCode: "pass",
                validationCode: "assert True",
                points: 10
            }
        ],
        createdAt: new Date().toISOString()
    });

    const params = {
        headers: {
            'Content-Type': 'application/json',
        },
    };

    const res = http.post(`${BASE_URL}/api/admin/exams`, payload, params);

    check(res, {
        'create exam status is 200': (r) => r.status === 200,
        'created exam has id': (r) => r.json('id') === newExamId,
    });
    sleep(3);
}
